[build-system]
requires = ["setuptools", "wheel", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "epoch-toolkit"
dynamic = ["version"]
dependencies = [
    "numpy",
    "pydantic"
]